/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.util.Random;

/**
 *
 * @author Lars Nordstrom <lars.nordstrom@jgy.se>
 */
public class Game extends javax.swing.JFrame {

    int playerScore = 0;
    int computerScore = 0;
    String playerChoice = "";
    String computerChoice = "";

    String choices[] = {"ROCK", "PAPER", "SCISSORS"};

    int scoreToWin = 3;
    Random random = new Random();

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnScissors = new javax.swing.JButton();
        btnPaper = new javax.swing.JButton();
        btnRock = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblOutcome = new javax.swing.JLabel();
        lblPlayerChoice = new javax.swing.JLabel();
        lblComputerChoice = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblPlayerScore = new javax.swing.JLabel();
        lblComputer = new javax.swing.JLabel();
        lblComputerScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnScissors.setText("Scissors");
        btnScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScissorsActionPerformed(evt);
            }
        });

        btnPaper.setText("Paper");
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperActionPerformed(evt);
            }
        });

        btnRock.setText("Rock");
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblOutcome.setText("Play Game!");

        lblPlayer.setText("Player");

        lblPlayerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerScore.setText("0");

        lblComputer.setText("Computer");

        lblComputerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComputerScore.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(lblPlayerChoice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRock)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPaper)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnScissors))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(lblOutcome)
                                        .addGap(35, 35, 35)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblComputerChoice))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPlayer))
                                .addGap(418, 418, 418)
                                .addComponent(lblComputer)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(473, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblComputerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlayer)
                            .addComponent(lblComputer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlayerScore))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblComputerScore)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutcome)
                    .addComponent(lblPlayerChoice)
                    .addComponent(lblComputerChoice))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRock)
                    .addComponent(btnPaper)
                    .addComponent(btnScissors))
                .addGap(39, 39, 39)
                .addComponent(btnReset)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        playerScore = 0;
        computerScore = 0;
        playerChoice = "";
        computerChoice = "";
        lblPlayerChoice.setText(playerChoice);
        lblComputerChoice.setText(computerChoice);
        lblPlayerScore.setText("0");
        lblComputerScore.setText("0");
        lblOutcome.setText("Play Game!");

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockActionPerformed
        // TODO add your handling code here:
        playerChoice = "ROCK";
        lblPlayerChoice.setText(playerChoice);
        computerChoice = choices[random.nextInt(3)];
        lblComputerChoice.setText(computerChoice);

        if (computerChoice.equals("SCISSORS")) {
            lblOutcome.setText("Player Wins!");
            playerScore += 1;
            lblPlayerScore.setText("" + playerScore);
        }

        if (computerChoice.equals("PAPER")) {
            lblOutcome.setText("Computer Wins!");
            computerScore += 1;
            lblComputerScore.setText("" + computerScore);
        }

        if (computerChoice.equals("ROCK")) {
            lblOutcome.setText("It´s a draw!");
        }

        if (playerScore == scoreToWin) {
            lblOutcome.setText("Player Wins The Game!");
        }

        if (computerScore == scoreToWin) {
            lblOutcome.setText("Computer Wins The Game!");
        }

    }//GEN-LAST:event_btnRockActionPerformed

    private void btnPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperActionPerformed
        // TODO add your handling code here:
        playerChoice = "PAPER";
        lblPlayerChoice.setText(playerChoice);
        computerChoice = choices[random.nextInt(3)];
        lblComputerChoice.setText(computerChoice);

        if (computerChoice.equals("ROCK")) {
            lblOutcome.setText("Player Wins!");
            playerScore += 1;
            lblPlayerScore.setText("" + playerScore);
        }

        if (computerChoice.equals("SCISSORS")) {
            lblOutcome.setText("Computer Wins!");
            computerScore += 1;
            lblComputerScore.setText("" + computerScore);
        }

        if (computerChoice.equals("PAPER")) {
            lblOutcome.setText("It´s a draw!");
        }

        if (playerScore == scoreToWin) {
            lblOutcome.setText("Player Wins The Game!");
        }

        if (computerScore == scoreToWin) {
            lblOutcome.setText("Computer Wins The Game!");
        }
    }//GEN-LAST:event_btnPaperActionPerformed

    private void btnScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScissorsActionPerformed
        // TODO add your handling code here:
        playerChoice = "SCISSORS";
        lblPlayerChoice.setText(playerChoice);
        computerChoice = choices[random.nextInt(3)];
        lblComputerChoice.setText(computerChoice);

        if (computerChoice.equals("PAPER")) {
            lblOutcome.setText("Player Wins!");
            playerScore += 1;
            lblPlayerScore.setText("" + playerScore);
        }

        if (computerChoice.equals("ROCK")) {
            lblOutcome.setText("Computer Wins!");
            computerScore += 1;
            lblComputerScore.setText("" + computerScore);
        }

        if (computerChoice.equals("SCISSORS")) {
            lblOutcome.setText("It´s a draw!");
        }

        if (playerScore == scoreToWin) {
            lblOutcome.setText("Player Wins The Game!");
        }

        if (computerScore == scoreToWin) {
            lblOutcome.setText("Computer Wins The Game!");
        }
    }//GEN-LAST:event_btnScissorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaper;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRock;
    private javax.swing.JButton btnScissors;
    private javax.swing.JLabel lblComputer;
    private javax.swing.JLabel lblComputerChoice;
    private javax.swing.JLabel lblComputerScore;
    private javax.swing.JLabel lblOutcome;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayerChoice;
    private javax.swing.JLabel lblPlayerScore;
    // End of variables declaration//GEN-END:variables
}
