/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.util.Random;

/**
 *
 * @author Lars Nordstrom <lars.nordstrom@jgy.se>
 */
public class Game extends javax.swing.JFrame {

    int playerScore = 0;
    int computerScore = 0;
    String playerChoice = "";
    String computerChoice = "";

    String choices[] = {"ROCK", "PAPER", "SCISSORS"};

    int scoreToWin = 3;
    Random random = new Random();

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnScissors = new javax.swing.JButton();
        btnPaper = new javax.swing.JButton();
        btnRock = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblOutcome = new javax.swing.JLabel();
        lblPlayerChoice = new javax.swing.JLabel("...");
        lblComputerChoice = new javax.swing.JLabel("...");
        lblPlayer = new javax.swing.JLabel();
        lblPlayerScore = new javax.swing.JLabel();
        lblComputer = new javax.swing.JLabel();
        lblComputerScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));
        setName("MainFrame"); // NOI18N

        btnScissors.setText("Scissors");
        btnScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHandler(evt);
            }
        });

        btnPaper.setText("Paper");
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHandler(evt);
            }
        });

        btnRock.setText("Rock");
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHandler(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHandler(evt);
            }
        });

        lblOutcome.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblOutcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutcome.setText("Play Game!");

        lblPlayerChoice.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblPlayerChoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerChoice.setText("...");

        lblComputerChoice.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblComputerChoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComputerChoice.setText("...");

        lblPlayer.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer.setText("Player");

        lblPlayerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerScore.setText("0");

        lblComputer.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblComputer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComputer.setText("Computer");

        lblComputerScore.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblComputerScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComputerScore.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPlayer)
                    .addComponent(lblPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComputerScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComputer))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRock)
                            .addGap(6, 6, 6)
                            .addComponent(btnPaper)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnScissors))
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayerChoice)
                        .addGap(18, 18, 18)
                        .addComponent(lblOutcome)
                        .addGap(18, 18, 18)
                        .addComponent(lblComputerChoice)))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPaper, btnReset, btnRock, btnScissors});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblComputer, lblComputerScore, lblPlayer, lblPlayerScore});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblComputerChoice, lblOutcome, lblPlayerChoice});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComputer)
                    .addComponent(lblPlayer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComputerScore)
                    .addComponent(lblPlayerScore))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutcome)
                    .addComponent(lblPlayerChoice)
                    .addComponent(lblComputerChoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnRock)
                    .addComponent(btnPaper)
                    .addComponent(btnScissors))
                .addGap(30, 30, 30)
                .addComponent(btnReset)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPaper, btnReset, btnRock, btnScissors});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblComputer, lblComputerChoice, lblComputerScore, lblOutcome, lblPlayer, lblPlayerChoice, lblPlayerScore});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHandler
        // TODO add your handling code here:
        if (evt.getSource() == btnRock) {

        }

        if (evt.getSource() == btnPaper) {

        }

        if (evt.getSource() == btnScissors) {

        }
        
        if (evt.getSource() == btnReset) {

        }
    }//GEN-LAST:event_buttonHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    public void checkMoves(String playerMove, String computerMove) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaper;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRock;
    private javax.swing.JButton btnScissors;
    private javax.swing.JLabel lblComputer;
    private javax.swing.JLabel lblComputerChoice;
    private javax.swing.JLabel lblComputerScore;
    private javax.swing.JLabel lblOutcome;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayerChoice;
    private javax.swing.JLabel lblPlayerScore;
    // End of variables declaration//GEN-END:variables
}
